#!/usr/bin/env python

import requests
import json
from datetime import datetime
import click

base_url = "https://api.darksky.net/forecast/"

api_key = "30b8b5a1ae8366829547a64d3c4d6f1e"

def convert_time(timestamp):
    return datetime.utcfromtimestamp(timestamp).strftime('%H:%M:%S')


def get_weather(lat,log):
    url = base_url + api_key + "/" + str(lat) + "," + str(log)
    response = requests.get(url)
    data = response.json()
    print("Time Zone {}".format(data['timezone']))
    for i in range(0,8):
        time = data['hourly']['data'][i]['time']
        summary = data['hourly']['data'][i]['summary']
        temp = data['hourly']['data'][i]['temperature']
        time = convert_time(time)
        print('Temperature at {}:{}, {}'.format(time,temp,summary))


@click.command()
@click.option('-lat',help="Latitude")
@click.option('-lon',help="Longitutde")
def main(lat,lon):
    if lat is not None and lon is not None:
        print("Today's Forecast --{}\n".format(datetime.now()))
        get_weather(lat,lon)
    else:
        print("Latitude and Longitude cannot be empty!!!")

if __name__ =='__main__':
    """
        pip install --editable .
    """
    main()


